Repository shardeum/core, pull requests merged in 2024-08, with the labels that each got.

#216 GOLD-145 : AJV addition and verification data check: binary_get_account_data_by_list
  src/types/GetAccountDataByListReq.ts
  src/types/GetAccountDataByListResp.ts
  src/types/ajv/GetAccountDataByListReq.ts
  src/types/ajv/GetAccountDataByListResp.ts
  src/types/enum/AJVSchemaEnum.ts
Labels: Review effort [1-5]: 2

#213 GOLD-146 : AJV addition and verification data check: binary_spread_appliedVoteHash
  src/types/ajv/Helpers.ts
  src/types/ajv/SpreadAppliedVoteHashReq.ts
  src/types/enum/AJVSchemaEnum.ts
  test/unit/src/types/SpreadAppliedVoteHashReq.test.ts
Labels: Review effort [1-5]: 2

#229 RED-220: always emit `node-deactivated` event
  src/p2p/NodeList.ts
Labels: Review effort [1-5]: 2

#226 Fix header and sender check in Comms
  src/p2p/Comms.ts
Labels: Review effort [1-5]: 2

#250 fix: convert the cache datastruct to be a map prevents proto pollute
  src/state-manager/TransactionConsensus.ts
Labels: Review effort [1-5]: 3

#255 PRI-53 : Harden debug middleware against replay attacks (sign the parameters and payload)
  src/network/debugMiddleware.ts
Labels: Review effort [1-5]: 4

#233 RED-247: Add null check for `queueEntry` when getting index value in the TransactionQueue processing loop
  src/state-manager/TransactionQueue.ts
Labels: Review effort [1-5]: 2

#252 PRI-54 : Prevent front running initial account data distribution
  src/state-manager/TransactionConsensus.ts
  src/state-manager/TransactionQueue.ts
  src/state-manager/index.ts
Labels: Review effort [1-5]: 3
