Repository shardeum/core, pull requests merged in 2024-10, with the labels that each got.

#285 RED-261: add cycleRecord validation
  src/config/server.ts
  src/p2p/Sync.ts
  src/shardus/shardus-types.ts
  src/types/ajv/CycleRecordSchema.ts
  src/types/ajv/Helpers.ts
  src/types/enum/AJVSchemaEnum.ts
  test/data/validCycleRecord.json
  test/unit/src/types/CycleRecordSchema.test.ts
Labels: Review effort [1-5]: 3

#302 GOLD-217: remove binary internal endpoint flags
  src/config/server.ts
  src/shardus/shardus-types.ts
Labels: Review effort [1-5]: 2

#294 GOLD-265 -- feat: archiver socketio now require a timestamped sig for replay prevent
  src/shardus/index.ts
Labels: Review effort [1-5]: 4

#293 BLUE-130 Global txreceipt forwarding
  package-lock.json
  package.json
  src/config/server.ts
  src/p2p/GlobalAccounts.ts
  src/shardus/index.ts
  src/shardus/shardus-types.ts
  src/state-manager/TransactionQueue.ts
  src/state-manager/index.ts
  src/state-manager/state-manager-types.ts
  src/types/MakeReceipReq.ts
  src/types/RequestTxAndStateReq.ts
  src/types/RequestTxAndStateResp.ts
  src/types/enum/InternalRouteEnum.ts
  test/unit/src/types/MakeReceiptReq.test.ts
Labels: Review effort [1-5]: 4
