Repository shardeum/core, pull requests merged in 2025-05, with the labels that each got.

#482 SHARD-2324 - Fix Defaults
  src/config/server.ts
Labels: Review effort 1/5

#484 Add error handling, address validation, and uniqueKeys check
  src/shardus/index.ts
  src/state-manager/TransactionQueue.ts
Labels: Review effort 2/5

#487 fix: pass by reference issue
  src/state-manager/TransactionConsensus.ts
Labels: Review effort 1/5

#486 Add counters for lost archiver in forwardDataToSubscribedArchivers
  src/p2p/Archivers.ts
Labels: Review effort 2/5

#488 feat : adds logging to archiver receipt retrieval
  src/state-manager/TransactionQueue.ts
Labels: Review effort 2/5

#490 added sec.md
  SECURITY.md
Labels: Review effort 1/5

#491 SHARD-2448: Add mechanism prevent txns with same tags into queue
  src/shardus/index.ts
  src/shardus/shardus-types.ts
  src/state-manager/TransactionQueue.ts
  src/state-manager/state-manager-types.ts
Labels: Review effort 3/5

#492 Create .nvmrc
  .nvmrc
Labels: Review effort 1/5
