Repository shardeum/core, pull requests merged in 2025-04, with the labels that each got.

#463 SHARD-2188 - add pdf to files list.
  package.json
Labels: Review effort 1/5

#465 SHARD-2199: add enableDebugFlags to server configuration
  src/config/server.ts
  src/shardus/shardus-types.ts
Labels: Review effort 1/5

#467 cherrypick main
  src/config/server.ts
  src/shardus/shardus-types.ts
Labels: Review effort 1/5

#471 Restore network changes.
  src/debug/debug.ts
  src/network/debugMiddleware.ts
  src/p2p/Archivers.ts
  src/p2p/CycleCreator.ts
  test/unit/src/network/debugMiddleware.test.ts
Labels: Review effort 4/5

#478 SHARD-2310: add kill node flag to core flags
  src/shardus/coreFlags.ts
  src/shardus/index.ts
Labels: Review effort 2/5

#476 SHARD-2308 : add configurable network latency simulation
  src/network/index.ts
  src/shardus/coreFlags.ts
Labels: Review effort 2/5

#477 SHARD-2309 : adds delay to SyncV2 operations
  src/p2p/SyncV2/index.ts
  src/shardus/coreFlags.ts
Labels: Review effort 2/5
