Repository shardeum/core, pull requests merged in 2025-03, with the labels that each got.

#435 SHARD-1960: add max response size
  src/config/server.ts
  src/http/customHttpFunctions.ts
  src/http/index.ts
  src/logger/index.ts
  src/p2p/Archivers.ts
  src/shardus/shardus-types.ts
  test/unit/src/http/customHttpFunctions.test.ts
Labels: Review effort 3/5

#437 SHARD-2037: Add keep-alive response during data collection for combined-debug
  README.md
  src/utils/profiler.ts
  test/unit/src/utils/profiler.test.ts
Labels: Review effort 2/5

#446 SHARD-2060: add option to turn off user/app tx
  src/config/server.ts
  src/p2p/ServiceQueue.ts
  src/shardus/index.ts
  src/shardus/shardus-types.ts
  src/state-manager/TransactionQueue.ts
Labels: Review effort 2/5

#443 SHARD-2063: Limit accounts in binary_get_account_data_with_queue_hints request
  src/state-manager/index.ts
Labels: Review effort 2/5

#442 test : add unit tests for debugMiddleware with comprehensive coverage for various middleware functions and scenarios
  test/unit/src/network/debugMiddleware.test.ts
Labels: Review effort 4/5

#441 feat : add unit tests for Utils module, covering compareQuery, sequentialQuery, robustQuery, attempt, generateUUID, getOurNodeIndex, and isNodeInRotationBounds functions.
  test/unit/src/p2p/Utils.test.ts
Labels: Review effort 3/5

#438 feat: implement unit tests for NodeList
  test/unit/src/p2p/NodeList.test.ts
Labels: Review effort 3/5

#449 SHARD-2099: add limits to `binary_repair_oos_accounts`
  src/config/server.ts
  src/shardus/shardus-types.ts
  src/state-manager/AccountPatcher.ts
Labels: Review effort 3/5

#430 Unit tests for ajv helpers
  test/unit/src/types/ajv/Helpers.test.ts
Labels: Review effort 3/5

#447 add tests for FifoCache
  test/unit/src/utils/fifoCache.test.ts
Labels: Review effort 2/5

#453 Merge network restore stuff
  src/config/server.ts
  src/logger/index.ts
  src/p2p/CycleCreator.ts
  src/p2p/Join/index.ts
  src/p2p/NodeList.ts
  src/p2p/Self.ts
  src/p2p/ServiceQueue.ts
  src/p2p/Sync.ts
  src/shardus/shardus-types.ts
  src/state-manager/AccountGlobals.ts
  src/state-manager/AccountPatcher.ts
  src/state-manager/AccountSync.ts
  src/state-manager/ArchiverDataSourceHelper.ts
  src/state-manager/ArchiverSyncTracker.ts
  src/state-manager/index.ts
  test/unit/src/p2p/NodeList.test.ts
  test/unit/src/p2p/Self.test.ts
Labels: Review effort 4/5

#445 test: Add comprehensive unit tests for Helpers.ts utility functions
  test/unit/src/types/Helpers.test.ts
Labels: Review effort 2/5

#448 add unit tests for src/state-manager/NodeSyncTracker.ts
  test/unit/src/state-manager/NodeSyncTracker.test.ts
Labels: Review effort 4/5

#454 SHARD-2079: core/set min requiredSigs to 3
  src/config/server.ts
  src/network/debugMiddleware.ts
  test/unit/src/network/debugMiddleware.test.ts
Labels: Review effort 2/5
